spring.application.name=metahelper

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

google.api.key=${GOOGLE_API_KEY:}
gemini.model=${GEMINI_MODEL:gemini-1.5-flash}
audio.amplitude.multiplier=${AUDIO_AMPLITUDE_MULTIPLIER:0.1}
